project_name: dockma
builds:
  - main: ./cmd/dockma.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -v
      - -mod=vendor # default since go 1.14
    ldflags:
      - -X github.com/martinnirtl/dockma/internal/buildinfo.version={{ .Version }}
      - -X github.com/martinnirtl/dockma/internal/buildinfo.commit={{ .Commit }}
      - -X github.com/martinnirtl/dockma/internal/buildinfo.date={{ .Date }}
    goos:
      - windows
      - darwin
      - linux
    ignore:
      - goos: darwin
        goarch: 386
archives:
  - name_template: "dockma-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
    wrap_in_directory: false
checksum:
  name_template: "dockma-{{ .Version }}-checksums.sha256"
  algorithm: sha256
release:
  github:
    owner: martinnirtl
    name: dockma
snapshot:
  name_template: "{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}"
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^update readme"
# signs:
#   - artifacts: checksum
brews:
  - name: dockma
    github:
      owner: martinnirtl
      name: homebrew-tap
    homepage: "https://github.com/martinnirtl/dockma"
    description: "Level up your docker-compose game!"
    test: |
      system "#{bin}/dockma version"
