version: "3"

services:
  backend:
    image: kennethreitz/httpbin:latest

  polling:
    build: ../polling-service
    image: polling-service:local
    environment:
      - PORT=4000
      - POLL_INTERVAL_MS=5000
      - API_BASEURL=http://${BACKEND_HOST} # dynamic address resolution by dockma
    ports:
      # - "HOST:CONTAINER"
      - "4000:4000"
