name: build
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      # - name: unshallow
      #   run: git fetch --prune --unshallow

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.DOCKMA_GH_TOKEN }}

      - name: Generate Go-Report
        uses: wei/curl@v1.1.1
        with:
          args: -X POST -F "repo=github.com/$GITHUB_REPOSITORY" https://goreportcard.com/checks
        continue-on-error: true
