version: "3"

services:
  backend:
    image: kennethreitz/httpbin:latest

  middleware:
    build: ../middleware-service
    image: middleware-service:local
    environment:
      - PORT=3500
      - BACKEND_BASEURL=http://${BACKEND_HOST} # dynamic address resolution by dockma

  polling:
    build: ../polling-service
    image: polling-service:local
    environment:
      - PORT=4000
      - POLL_INTERVAL_MS=5000
      - API_BASEURL=http://${MIDDLEWARE_HOST}:3500 # dynamic address resolution by dockma
